classdef model < handle
    % MODEL Class to manage radar data and file I/O
    
    properties
        M % Matrix to store current radar data sweeps
    end

    methods
        function obj = model()
            % Constructor: Initialize with an empty data matrix
            obj.M = [];             
        end

        function loadData(obj)
            % loadData Reads the CSV generated by the Python radar script.
            % It includes a timeout mechanism to wait for the file to appear
            % after being cleared at the start of the session.
            
            fileName = 'radar_capture.csv';
            maxRetries = 10; % Max attempts to find the file
            pauseDuration = 0.1; % Seconds to wait between retries
            
            % Wait loop to ensure the file exists before reading
            % (Useful after the initial clearance of the CSV)
            attempt = 0;
            while ~exist(fileName, 'file') && attempt < maxRetries
                pause(pauseDuration);
                attempt = attempt + 1;
            end

            if exist(fileName, 'file')
                try
                    % Read the numeric matrix from the CSV
                    obj.M = readmatrix(fileName);
                    
                    % Basic validation to ensure data isn't empty
                    if isempty(obj.M)
                        warning('Model: radar_capture.csv is empty.');
                    end
                catch ME
                    warning('Model: Failed to read CSV. Error: %s');
                end
            else
                warning('Model: %s not found after waiting.', fileName);
            end
        end
    end
end