classdef model < handle
    properties
        M % Matrix to store current radar data
    end

    methods
        function obj = model()
            obj.M = [];             
        end

        function loadData(obj)
            % Reads the CSV generated by the Python script
            if exist('radar_capture.csv', 'file')
                obj.M = readmatrix('radar_capture.csv');
            else
                warning('radar_capture.csv not found.');
            end
        end
    end
end