classdef model < handle

    properties
        M
    end

    methods
        function obj = model()
            obj.M = [];
        end

        function loadData(obj)
<<<<<<< Updated upstream
            % Reads the CSV generated by the Python script
            if exist('radar_capture.csv', 'file')
                obj.M = readmatrix('radar_capture.csv');
                
            else
                warning('radar_capture.csv not found.');
            end
=======
            obj.M = readmatrix('radar_capture.csv');
            % filter / data processing goes here
>>>>>>> Stashed changes
        end
    end
end
